---
settings:
  name: Ransomware Protection
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: Schutz vor Ransomware
    url: "/index.html"
  - title: Versionshinweise
    url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über Ransomware-Schutz
      url: "/concept-ransomware-protection.html"
    - title: Überwachen Sie Ransomware-Warnungen im Benachrichtigungszentrum
      url: "/task-monitor-ransomware-alerts.html"
  - title: Verwenden Sie Ransomware-Schutz
    entries:
    - title: Managen Sie Cyber-Sicherheitsempfehlungen für Ihre Daten
      url: "/task-analyze-ransomware-data.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Erfahren Sie mehr über Ransomware-Schutz
      url: concept-ransomware-protection.html
    - title: Was ist neu
      url: whats-new.html
  - title: Managen Sie Empfehlungen zur Cybersicherheit
    links:
    - title: Anzeige von oberen Daten-Repositorys nach Datenempfindlichkeit
      url: task-analyze-ransomware-data.html#top-data-repositories-by-data-sensitivity
    - title: Benutzer anzeigen, die zu Domänenadministratorgruppen hinzugefügt wurden
      url: task-analyze-ransomware-data.html#domain-administrator-group-control
    - title: Anzeigen von Daten, die nach offenen Berechtigungen aufgeführt sind
      url: task-analyze-ransomware-data.html#data-listed-by-types-of-open-permissions
    - title: Zeigen Sie die in verschlüsselten Dateien aufgelisteten Daten an
      url: task-analyze-ransomware-data.html#data-listed-by-encrypted-files
    - title: So schützen Sie Ihre ONTAP Systeme sicher vor Ransomware
      url: task-analyze-ransomware-data.html#status-of-ontap-systems-hardening
  - title: Blogs Community
    links:
    - title: NetApp Community
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: BlueXP-Blog
      url: https://cloud.netapp.com/blog
    - title: Cloud-Webinare
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Alle BlueXP-Dokumentationen
